# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.drawWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.drawWidget.setObjectName("drawWidget")
        self.BezierCurve = QtWidgets.QWidget()
        self.BezierCurve.setObjectName("BezierCurve")
        self.formLayout = QtWidgets.QFormLayout(self.BezierCurve)
        self.formLayout.setObjectName("formLayout")
        self.degreeBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.degreeBezierlabel.setObjectName("degreeBezierlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.degreeBezierlabel)
        self.degreeBeziercomboBox = QtWidgets.QComboBox(self.BezierCurve)
        self.degreeBeziercomboBox.setObjectName("degreeBeziercomboBox")
        self.degreeBeziercomboBox.addItem("")
        self.degreeBeziercomboBox.addItem("")
        self.degreeBeziercomboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.degreeBeziercomboBox)
        self.stepsBeizerlabel = QtWidgets.QLabel(self.BezierCurve)
        self.stepsBeizerlabel.setObjectName("stepsBeizerlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stepsBeizerlabel)
        self.stepsBeizerspinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.stepsBeizerspinBox.setMinimum(1)
        self.stepsBeizerspinBox.setProperty("value", 10)
        self.stepsBeizerspinBox.setObjectName("stepsBeizerspinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stepsBeizerspinBox)
        self.line_2 = QtWidgets.QFrame(self.BezierCurve)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.degreeMultiBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.degreeMultiBezierlabel.setObjectName("degreeMultiBezierlabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.degreeMultiBezierlabel)
        self.degreeMultiBeziercomboBox = QtWidgets.QComboBox(self.BezierCurve)
        self.degreeMultiBeziercomboBox.setObjectName("degreeMultiBeziercomboBox")
        self.degreeMultiBeziercomboBox.addItem("")
        self.degreeMultiBeziercomboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.degreeMultiBeziercomboBox)
        self.drawBezierBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawBezierBtn.setObjectName("drawBezierBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.drawBezierBtn)
        self.stepsMultiBezierspinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.stepsMultiBezierspinBox.setMinimum(1)
        self.stepsMultiBezierspinBox.setProperty("value", 10)
        self.stepsMultiBezierspinBox.setObjectName("stepsMultiBezierspinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.stepsMultiBezierspinBox)
        self.stepsMultiBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.stepsMultiBezierlabel.setObjectName("stepsMultiBezierlabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.stepsMultiBezierlabel)
        self.drawMultiBezierBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawMultiBezierBtn.setObjectName("drawMultiBezierBtn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.drawMultiBezierBtn)
        self.line = QtWidgets.QFrame(self.BezierCurve)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.steps_uBezierSurfacelabel = QtWidgets.QLabel(self.BezierCurve)
        self.steps_uBezierSurfacelabel.setObjectName("steps_uBezierSurfacelabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.steps_uBezierSurfacelabel)
        self.steps_vBezierSurfacelabel = QtWidgets.QLabel(self.BezierCurve)
        self.steps_vBezierSurfacelabel.setObjectName("steps_vBezierSurfacelabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.steps_vBezierSurfacelabel)
        self.horizontalSlider = QtWidgets.QSlider(self.BezierCurve)
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.clearBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.clearBtn.setObjectName("clearBtn")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.clearBtn)
        self.steps_uBezierSurfacespinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.steps_uBezierSurfacespinBox.setMinimum(1)
        self.steps_uBezierSurfacespinBox.setProperty("value", 10)
        self.steps_uBezierSurfacespinBox.setObjectName("steps_uBezierSurfacespinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.steps_uBezierSurfacespinBox)
        self.steps_vBezierSurfacespinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.steps_vBezierSurfacespinBox.setMinimum(1)
        self.steps_vBezierSurfacespinBox.setProperty("value", 10)
        self.steps_vBezierSurfacespinBox.setObjectName("steps_vBezierSurfacespinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.steps_vBezierSurfacespinBox)
        self.displayMeshcheckBox = QtWidgets.QCheckBox(self.BezierCurve)
        self.displayMeshcheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.displayMeshcheckBox.setObjectName("displayMeshcheckBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.displayMeshcheckBox)
        self.drawBezierSurfaceBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawBezierSurfaceBtn.setObjectName("drawBezierSurfaceBtn")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.drawBezierSurfaceBtn)
        self.line_3 = QtWidgets.QFrame(self.BezierCurve)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.splitBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.splitBtn.setObjectName("splitBtn")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.splitBtn)
        self.pushButton = QtWidgets.QPushButton(self.BezierCurve)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.drawWidget.addTab(self.BezierCurve, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.knotlabel = QtWidgets.QLabel(self.tab)
        self.knotlabel.setObjectName("knotlabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.knotlabel)
        self.knotTypecomboBox = QtWidgets.QComboBox(self.tab)
        self.knotTypecomboBox.setObjectName("knotTypecomboBox")
        self.knotTypecomboBox.addItem("")
        self.knotTypecomboBox.addItem("")
        self.knotTypecomboBox.addItem("")
        self.knotTypecomboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.knotTypecomboBox)
        self.bSplineBtn = QtWidgets.QPushButton(self.tab)
        self.bSplineBtn.setObjectName("bSplineBtn")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.bSplineBtn)
        self.drawWidget.addTab(self.tab, "")
        self.horizontalLayout_3.addWidget(self.drawWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout_2.addWidget(self.openGLWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelect_mode = QtWidgets.QAction(MainWindow)
        self.actionSelect_mode.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/mouse-pointer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_mode.setIcon(icon)
        self.actionSelect_mode.setObjectName("actionSelect_mode")
        self.actionPencil = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPencil.setIcon(icon1)
        self.actionPencil.setObjectName("actionPencil")
        self.toolBar.addAction(self.actionSelect_mode)
        self.toolBar.addAction(self.actionPencil)

        self.retranslateUi(MainWindow)
        self.drawWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.degreeBezierlabel.setText(_translate("MainWindow", "Degree"))
        self.degreeBeziercomboBox.setItemText(0, _translate("MainWindow", "Quadratic"))
        self.degreeBeziercomboBox.setItemText(1, _translate("MainWindow", "Cubic"))
        self.degreeBeziercomboBox.setItemText(2, _translate("MainWindow", "N-degree"))
        self.stepsBeizerlabel.setText(_translate("MainWindow", "Steps"))
        self.degreeMultiBezierlabel.setText(_translate("MainWindow", "Degree"))
        self.degreeMultiBeziercomboBox.setItemText(0, _translate("MainWindow", "Quadratic"))
        self.degreeMultiBeziercomboBox.setItemText(1, _translate("MainWindow", "Cubic"))
        self.drawBezierBtn.setText(_translate("MainWindow", "Draw Bezier Curve"))
        self.stepsMultiBezierlabel.setText(_translate("MainWindow", "Steps"))
        self.drawMultiBezierBtn.setText(_translate("MainWindow", "Draw Multi-Bezier"))
        self.steps_uBezierSurfacelabel.setText(_translate("MainWindow", "Steps-u"))
        self.steps_vBezierSurfacelabel.setText(_translate("MainWindow", "Steps-v"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.displayMeshcheckBox.setText(_translate("MainWindow", "Display Mesh"))
        self.drawBezierSurfaceBtn.setText(_translate("MainWindow", "Draw Bezier Surface"))
        self.splitBtn.setText(_translate("MainWindow", "Split curve"))
        self.pushButton.setText(_translate("MainWindow", "Bezier circle"))
        self.drawWidget.setTabText(self.drawWidget.indexOf(self.BezierCurve), _translate("MainWindow", "Bezier"))
        self.knotlabel.setText(_translate("MainWindow", "Knots"))
        self.knotTypecomboBox.setItemText(0, _translate("MainWindow", "Clamped"))
        self.knotTypecomboBox.setItemText(1, _translate("MainWindow", "Bezier"))
        self.knotTypecomboBox.setItemText(2, _translate("MainWindow", "Open"))
        self.knotTypecomboBox.setItemText(3, _translate("MainWindow", "Closed"))
        self.bSplineBtn.setText(_translate("MainWindow", "Draw B spline"))
        self.drawWidget.setTabText(self.drawWidget.indexOf(self.tab), _translate("MainWindow", "B-Spline"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSelect_mode.setText(_translate("MainWindow", "Select mode"))
        self.actionPencil.setText(_translate("MainWindow", "Pencil"))
        self.actionPencil.setToolTip(_translate("MainWindow", "Draw point"))
