# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 108, 193))
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.curve_tab = QtWidgets.QWidget()
        self.curve_tab.setObjectName("curve_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.curve_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.curve_tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.push_button_bezier_quad = QtWidgets.QPushButton(self.curve_tab)
        self.push_button_bezier_quad.setObjectName("push_button_bezier_quad")
        self.verticalLayout.addWidget(self.push_button_bezier_quad)
        self.push_button_bezier_cubic = QtWidgets.QPushButton(self.curve_tab)
        self.push_button_bezier_cubic.setObjectName("push_button_bezier_cubic")
        self.verticalLayout.addWidget(self.push_button_bezier_cubic)
        self.push_button_bezier_multi = QtWidgets.QPushButton(self.curve_tab)
        self.push_button_bezier_multi.setObjectName("push_button_bezier_multi")
        self.verticalLayout.addWidget(self.push_button_bezier_multi)
        self.pushButton_2 = QtWidgets.QPushButton(self.curve_tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.curve_tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.curve_tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.tabWidget.addTab(self.curve_tab, "")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(-10, 0, 801, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(801, 0))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        self.menuStart = QtWidgets.QMenu(self.menubar)
        self.menuStart.setObjectName("menuStart")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionMove = QtWidgets.QAction(MainWindow)
        self.actionMove.setObjectName("actionMove")
        self.menuStart.addAction(self.actionNew)
        self.menuStart.addAction(self.actionOpen)
        self.menuStart.addAction(self.actionSave)
        self.menuStart.addAction(self.actionQuit)
        self.menuStart.addSeparator()
        self.menuStart.addSeparator()
        self.menubar.addAction(self.menuStart.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSelect)
        self.toolBar.addAction(self.actionMove)
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label.setText(_translate("MainWindow", "Bezier:"))
        self.push_button_bezier_quad.setText(_translate("MainWindow", "QuadBezier"))
        self.push_button_bezier_cubic.setText(_translate("MainWindow", "CubicBezier"))
        self.push_button_bezier_multi.setText(_translate("MainWindow", "MultiBezier"))
        self.pushButton_2.setText(_translate("MainWindow", "Circle"))
        self.label_2.setText(_translate("MainWindow", "Nurbs:"))
        self.pushButton_3.setText(_translate("MainWindow", "Nurbs Curve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.curve_tab), _translate("MainWindow", "Curve"))
        self.menuStart.setTitle(_translate("MainWindow", "Start"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear the palatte"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionSelect.setToolTip(_translate("MainWindow", "Select an item"))
        self.actionMove.setText(_translate("MainWindow", "Move"))
        self.actionMove.setToolTip(_translate("MainWindow", "Move an item"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
