# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.drawWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.drawWidget.setObjectName("drawWidget")
        self.BezierCurve = QtWidgets.QWidget()
        self.BezierCurve.setObjectName("BezierCurve")
        self.formLayout = QtWidgets.QFormLayout(self.BezierCurve)
        self.formLayout.setObjectName("formLayout")
        self.degreeBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.degreeBezierlabel.setObjectName("degreeBezierlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.degreeBezierlabel)
        self.degreeBeziercomboBox = QtWidgets.QComboBox(self.BezierCurve)
        self.degreeBeziercomboBox.setObjectName("degreeBeziercomboBox")
        self.degreeBeziercomboBox.addItem("")
        self.degreeBeziercomboBox.addItem("")
        self.degreeBeziercomboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.degreeBeziercomboBox)
        self.stepsBeizerlabel = QtWidgets.QLabel(self.BezierCurve)
        self.stepsBeizerlabel.setObjectName("stepsBeizerlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stepsBeizerlabel)
        self.stepsBeizerspinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.stepsBeizerspinBox.setMinimum(1)
        self.stepsBeizerspinBox.setMaximum(100)
        self.stepsBeizerspinBox.setProperty("value", 10)
        self.stepsBeizerspinBox.setObjectName("stepsBeizerspinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stepsBeizerspinBox)
        self.drawBezierBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawBezierBtn.setObjectName("drawBezierBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.drawBezierBtn)
        self.elevateDegreeBezierCurveBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.elevateDegreeBezierCurveBtn.setObjectName("elevateDegreeBezierCurveBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.elevateDegreeBezierCurveBtn)
        self.line_2 = QtWidgets.QFrame(self.BezierCurve)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.degreeMultiBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.degreeMultiBezierlabel.setObjectName("degreeMultiBezierlabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.degreeMultiBezierlabel)
        self.degreeMultiBeziercomboBox = QtWidgets.QComboBox(self.BezierCurve)
        self.degreeMultiBeziercomboBox.setObjectName("degreeMultiBeziercomboBox")
        self.degreeMultiBeziercomboBox.addItem("")
        self.degreeMultiBeziercomboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.degreeMultiBeziercomboBox)
        self.stepsMultiBezierlabel = QtWidgets.QLabel(self.BezierCurve)
        self.stepsMultiBezierlabel.setObjectName("stepsMultiBezierlabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.stepsMultiBezierlabel)
        self.stepsMultiBezierspinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.stepsMultiBezierspinBox.setMinimum(1)
        self.stepsMultiBezierspinBox.setMaximum(100)
        self.stepsMultiBezierspinBox.setProperty("value", 10)
        self.stepsMultiBezierspinBox.setObjectName("stepsMultiBezierspinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.stepsMultiBezierspinBox)
        self.drawMultiBezierBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawMultiBezierBtn.setObjectName("drawMultiBezierBtn")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.drawMultiBezierBtn)
        self.line = QtWidgets.QFrame(self.BezierCurve)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.steps_uBezierSurfacelabel = QtWidgets.QLabel(self.BezierCurve)
        self.steps_uBezierSurfacelabel.setObjectName("steps_uBezierSurfacelabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.steps_uBezierSurfacelabel)
        self.steps_uBezierSurfacespinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.steps_uBezierSurfacespinBox.setMinimum(1)
        self.steps_uBezierSurfacespinBox.setMaximum(100)
        self.steps_uBezierSurfacespinBox.setProperty("value", 10)
        self.steps_uBezierSurfacespinBox.setObjectName("steps_uBezierSurfacespinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.steps_uBezierSurfacespinBox)
        self.steps_vBezierSurfacelabel = QtWidgets.QLabel(self.BezierCurve)
        self.steps_vBezierSurfacelabel.setObjectName("steps_vBezierSurfacelabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.steps_vBezierSurfacelabel)
        self.steps_vBezierSurfacespinBox = QtWidgets.QSpinBox(self.BezierCurve)
        self.steps_vBezierSurfacespinBox.setMinimum(1)
        self.steps_vBezierSurfacespinBox.setMaximum(100)
        self.steps_vBezierSurfacespinBox.setProperty("value", 10)
        self.steps_vBezierSurfacespinBox.setObjectName("steps_vBezierSurfacespinBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.steps_vBezierSurfacespinBox)
        self.displayMeshcheckBox = QtWidgets.QCheckBox(self.BezierCurve)
        self.displayMeshcheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.displayMeshcheckBox.setObjectName("displayMeshcheckBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.displayMeshcheckBox)
        self.drawBezierSurfaceBtn = QtWidgets.QPushButton(self.BezierCurve)
        self.drawBezierSurfaceBtn.setObjectName("drawBezierSurfaceBtn")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.drawBezierSurfaceBtn)
        self.line_3 = QtWidgets.QFrame(self.BezierCurve)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.drawWidget.addTab(self.BezierCurve, "")
        self.B_Spline = QtWidgets.QWidget()
        self.B_Spline.setObjectName("B_Spline")
        self.formLayout_2 = QtWidgets.QFormLayout(self.B_Spline)
        self.formLayout_2.setObjectName("formLayout_2")
        self.knotlabel = QtWidgets.QLabel(self.B_Spline)
        self.knotlabel.setObjectName("knotlabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.knotlabel)
        self.knotTypecomboBox = QtWidgets.QComboBox(self.B_Spline)
        self.knotTypecomboBox.setObjectName("knotTypecomboBox")
        self.knotTypecomboBox.addItem("")
        self.knotTypecomboBox.addItem("")
        self.knotTypecomboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.knotTypecomboBox)
        self.degreeBSpline_label = QtWidgets.QLabel(self.B_Spline)
        self.degreeBSpline_label.setObjectName("degreeBSpline_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.degreeBSpline_label)
        self.degreeBSpline_spinBox = QtWidgets.QSpinBox(self.B_Spline)
        self.degreeBSpline_spinBox.setMaximum(100)
        self.degreeBSpline_spinBox.setProperty("value", 2)
        self.degreeBSpline_spinBox.setObjectName("degreeBSpline_spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.degreeBSpline_spinBox)
        self.bSplineBtn = QtWidgets.QPushButton(self.B_Spline)
        self.bSplineBtn.setObjectName("bSplineBtn")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.bSplineBtn)
        self.line_4 = QtWidgets.QFrame(self.B_Spline)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.line_4)
        self.divsBSplineSurface_label = QtWidgets.QLabel(self.B_Spline)
        self.divsBSplineSurface_label.setObjectName("divsBSplineSurface_label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.divsBSplineSurface_label)
        self.divsSplineSurfaceBox_spinBox = QtWidgets.QSpinBox(self.B_Spline)
        self.divsSplineSurfaceBox_spinBox.setMinimum(1)
        self.divsSplineSurfaceBox_spinBox.setMaximum(100)
        self.divsSplineSurfaceBox_spinBox.setProperty("value", 10)
        self.divsSplineSurfaceBox_spinBox.setObjectName("divsSplineSurfaceBox_spinBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.divsSplineSurfaceBox_spinBox)
        self.knotlabel_2 = QtWidgets.QLabel(self.B_Spline)
        self.knotlabel_2.setObjectName("knotlabel_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.knotlabel_2)
        self.bSplineSurface_comboBox = QtWidgets.QComboBox(self.B_Spline)
        self.bSplineSurface_comboBox.setObjectName("bSplineSurface_comboBox")
        self.bSplineSurface_comboBox.addItem("")
        self.bSplineSurface_comboBox.addItem("")
        self.bSplineSurface_comboBox.addItem("")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bSplineSurface_comboBox)
        self.degreeBSplineSurface_label = QtWidgets.QLabel(self.B_Spline)
        self.degreeBSplineSurface_label.setObjectName("degreeBSplineSurface_label")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.degreeBSplineSurface_label)
        self.degreeBSplineSurface_spinBox = QtWidgets.QSpinBox(self.B_Spline)
        self.degreeBSplineSurface_spinBox.setMaximum(100)
        self.degreeBSplineSurface_spinBox.setProperty("value", 3)
        self.degreeBSplineSurface_spinBox.setObjectName("degreeBSplineSurface_spinBox")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.degreeBSplineSurface_spinBox)
        self.bSplineSurface_displayTexture_checkBox = QtWidgets.QCheckBox(self.B_Spline)
        self.bSplineSurface_displayTexture_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bSplineSurface_displayTexture_checkBox.setObjectName("bSplineSurface_displayTexture_checkBox")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.bSplineSurface_displayTexture_checkBox)
        self.drawBSplineSurfaceBtn = QtWidgets.QPushButton(self.B_Spline)
        self.drawBSplineSurfaceBtn.setObjectName("drawBSplineSurfaceBtn")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.drawBSplineSurfaceBtn)
        self.bsplineModel_Btn = QtWidgets.QPushButton(self.B_Spline)
        self.bsplineModel_Btn.setObjectName("bsplineModel_Btn")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.bsplineModel_Btn)
        self.bsplineTexture_Btn = QtWidgets.QPushButton(self.B_Spline)
        self.bsplineTexture_Btn.setObjectName("bsplineTexture_Btn")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.bsplineTexture_Btn)
        self.drawWidget.addTab(self.B_Spline, "")
        self.NURBS = QtWidgets.QWidget()
        self.NURBS.setObjectName("NURBS")
        self.formLayout_3 = QtWidgets.QFormLayout(self.NURBS)
        self.formLayout_3.setObjectName("formLayout_3")
        self.NURBS_knotlabel = QtWidgets.QLabel(self.NURBS)
        self.NURBS_knotlabel.setObjectName("NURBS_knotlabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.NURBS_knotlabel)
        self.NURBS_knotTypecomboBox = QtWidgets.QComboBox(self.NURBS)
        self.NURBS_knotTypecomboBox.setObjectName("NURBS_knotTypecomboBox")
        self.NURBS_knotTypecomboBox.addItem("")
        self.NURBS_knotTypecomboBox.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.NURBS_knotTypecomboBox)
        self.weightNURBS_label = QtWidgets.QLabel(self.NURBS)
        self.weightNURBS_label.setObjectName("weightNURBS_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.weightNURBS_label)
        self.weightNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.weightNURBS_Btn.setObjectName("weightNURBS_Btn")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weightNURBS_Btn)
        self.degreeNURBS_label = QtWidgets.QLabel(self.NURBS)
        self.degreeNURBS_label.setObjectName("degreeNURBS_label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.degreeNURBS_label)
        self.degreeNURBS_spinBox = QtWidgets.QSpinBox(self.NURBS)
        self.degreeNURBS_spinBox.setMaximum(100)
        self.degreeNURBS_spinBox.setProperty("value", 2)
        self.degreeNURBS_spinBox.setObjectName("degreeNURBS_spinBox")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.degreeNURBS_spinBox)
        self.drawNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawNURBS_Btn.sizePolicy().hasHeightForWidth())
        self.drawNURBS_Btn.setSizePolicy(sizePolicy)
        self.drawNURBS_Btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.drawNURBS_Btn.setObjectName("drawNURBS_Btn")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.drawNURBS_Btn)
        self.line_5 = QtWidgets.QFrame(self.NURBS)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.line_5)
        self.circleNURBS_btn = QtWidgets.QPushButton(self.NURBS)
        self.circleNURBS_btn.setObjectName("circleNURBS_btn")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.circleNURBS_btn)
        self.bilinearNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.bilinearNURBS_Btn.setObjectName("bilinearNURBS_Btn")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.bilinearNURBS_Btn)
        self.sphereNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.sphereNURBS_Btn.setObjectName("sphereNURBS_Btn")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.sphereNURBS_Btn)
        self.torusNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.torusNURBS_Btn.setObjectName("torusNURBS_Btn")
        self.formLayout_3.setWidget(20, QtWidgets.QFormLayout.SpanningRole, self.torusNURBS_Btn)
        self.revolutedShapeNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.revolutedShapeNURBS_Btn.setObjectName("revolutedShapeNURBS_Btn")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.revolutedShapeNURBS_Btn)
        self.cylinderNURBS_Btn = QtWidgets.QPushButton(self.NURBS)
        self.cylinderNURBS_Btn.setObjectName("cylinderNURBS_Btn")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.cylinderNURBS_Btn)
        self.drawWidget.addTab(self.NURBS, "")
        self.horizontalLayout.addWidget(self.drawWidget)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.scenetreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.scenetreeWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.scenetreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.scenetreeWidget.setObjectName("scenetreeWidget")
        self.horizontalLayout.addWidget(self.scenetreeWidget)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelect_mode = QtWidgets.QAction(MainWindow)
        self.actionSelect_mode.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/mouse-pointer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_mode.setIcon(icon)
        self.actionSelect_mode.setObjectName("actionSelect_mode")
        self.actionPencil = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPencil.setIcon(icon1)
        self.actionPencil.setObjectName("actionPencil")
        self.actionClearScreen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Icons/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearScreen.setIcon(icon2)
        self.actionClearScreen.setObjectName("actionClearScreen")
        self.toolBar.addAction(self.actionSelect_mode)
        self.toolBar.addAction(self.actionPencil)
        self.toolBar.addAction(self.actionClearScreen)

        self.retranslateUi(MainWindow)
        self.drawWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.degreeBezierlabel.setText(_translate("MainWindow", "Degree"))
        self.degreeBeziercomboBox.setItemText(0, _translate("MainWindow", "Quadratic"))
        self.degreeBeziercomboBox.setItemText(1, _translate("MainWindow", "Cubic"))
        self.degreeBeziercomboBox.setItemText(2, _translate("MainWindow", "N-degree"))
        self.stepsBeizerlabel.setText(_translate("MainWindow", "Steps"))
        self.drawBezierBtn.setText(_translate("MainWindow", "Draw Bezier Curve"))
        self.elevateDegreeBezierCurveBtn.setText(_translate("MainWindow", "Elevate Degree"))
        self.degreeMultiBezierlabel.setText(_translate("MainWindow", "Degree"))
        self.degreeMultiBeziercomboBox.setItemText(0, _translate("MainWindow", "Quadratic"))
        self.degreeMultiBeziercomboBox.setItemText(1, _translate("MainWindow", "Cubic"))
        self.stepsMultiBezierlabel.setText(_translate("MainWindow", "Steps"))
        self.drawMultiBezierBtn.setText(_translate("MainWindow", "Draw Multi-Bezier"))
        self.steps_uBezierSurfacelabel.setText(_translate("MainWindow", "Steps-u"))
        self.steps_vBezierSurfacelabel.setText(_translate("MainWindow", "Steps-v"))
        self.displayMeshcheckBox.setText(_translate("MainWindow", "Display Mesh"))
        self.drawBezierSurfaceBtn.setText(_translate("MainWindow", "Draw Bezier Surface"))
        self.drawWidget.setTabText(self.drawWidget.indexOf(self.BezierCurve), _translate("MainWindow", "Bezier"))
        self.knotlabel.setText(_translate("MainWindow", "Knots Type"))
        self.knotTypecomboBox.setItemText(0, _translate("MainWindow", "Clamped"))
        self.knotTypecomboBox.setItemText(1, _translate("MainWindow", "Open"))
        self.knotTypecomboBox.setItemText(2, _translate("MainWindow", "Closed"))
        self.degreeBSpline_label.setText(_translate("MainWindow", "Degree"))
        self.bSplineBtn.setText(_translate("MainWindow", "Draw B-Spline"))
        self.divsBSplineSurface_label.setText(_translate("MainWindow", "Steps"))
        self.knotlabel_2.setText(_translate("MainWindow", "Knots Type"))
        self.bSplineSurface_comboBox.setItemText(0, _translate("MainWindow", "Clamped"))
        self.bSplineSurface_comboBox.setItemText(1, _translate("MainWindow", "Open"))
        self.bSplineSurface_comboBox.setItemText(2, _translate("MainWindow", "Closed"))
        self.degreeBSplineSurface_label.setText(_translate("MainWindow", "Degree"))
        self.bSplineSurface_displayTexture_checkBox.setText(_translate("MainWindow", "Display Texture"))
        self.drawBSplineSurfaceBtn.setText(_translate("MainWindow", "Draw B-Spline Surface"))
        self.bsplineModel_Btn.setText(_translate("MainWindow", "Load Model"))
        self.bsplineTexture_Btn.setText(_translate("MainWindow", "Change"))
        self.drawWidget.setTabText(self.drawWidget.indexOf(self.B_Spline), _translate("MainWindow", "B-Spline"))
        self.NURBS_knotlabel.setText(_translate("MainWindow", "Knots Type"))
        self.NURBS_knotTypecomboBox.setItemText(0, _translate("MainWindow", "Clamped"))
        self.NURBS_knotTypecomboBox.setItemText(1, _translate("MainWindow", "Open"))
        self.weightNURBS_label.setText(_translate("MainWindow", "Weight"))
        self.weightNURBS_Btn.setText(_translate("MainWindow", "Change"))
        self.degreeNURBS_label.setText(_translate("MainWindow", "Degree"))
        self.drawNURBS_Btn.setText(_translate("MainWindow", "NURBS Curve"))
        self.circleNURBS_btn.setText(_translate("MainWindow", " NURBS Circle"))
        self.bilinearNURBS_Btn.setText(_translate("MainWindow", " NURBS Bilinear"))
        self.sphereNURBS_Btn.setText(_translate("MainWindow", " NURBS Sphere"))
        self.torusNURBS_Btn.setText(_translate("MainWindow", " NURBS Torus"))
        self.revolutedShapeNURBS_Btn.setText(_translate("MainWindow", " NURBS Surface of Revolution"))
        self.cylinderNURBS_Btn.setText(_translate("MainWindow", " NURBS Cylinder"))
        self.drawWidget.setTabText(self.drawWidget.indexOf(self.NURBS), _translate("MainWindow", "NURBS"))
        self.scenetreeWidget.headerItem().setText(0, _translate("MainWindow", "Scene"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSelect_mode.setText(_translate("MainWindow", "Select mode"))
        self.actionPencil.setText(_translate("MainWindow", "Pencil"))
        self.actionPencil.setToolTip(_translate("MainWindow", "Draw point"))
        self.actionClearScreen.setText(_translate("MainWindow", "ClearScreen"))
